replicaCount: 2

image:
  repository: nikhil/search-service
  pullPolicy: Always
  tag: "1.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 8060

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

securityContext:
   readOnlyRootFilesystem: false
   runAsNonRoot: false