apiVersion: apps/v1
kind: Deployment
metadata:
  name: marktek-iam
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: marktek-iam
  template:
    metadata:
      labels:
        app: marktek-iam
    spec:
      containers:
      - name: marktek-iam
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: "1"
        ports:
        - containerPort: 8080