apiVersion: v1
kind: Service
metadata:
  name: marktek-iam
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: marktek-iam
