{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marktek-iam-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "{{ index .Values.ingress.hosts 0 "host" }}"
    http:
      paths:
      - pathType: {{ index .Values.ingress.hosts 0 "paths" 0 "pathType" }}
        path: "{{ index .Values.ingress.hosts 0 "paths" 0 "path" }}"
        backend:
          service:
            name: marktek-iam
            port:
              number: 80
{{- end }}