server:
  port: 8081

spring:
  application:
    name: paymentservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: bijaya
    password: bijaya
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      open-in-view: false
      generate-ddl: false
      properties:
        hibernate.format_sql: false
  kafka:
    bootstrap-servers: localhost:9092
springdoc :
  swagger-ui:
    path: /swagger-ui-payment.html
    api-docs:
      path: /payment-openapi
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  flyway:
#    enabled: true
#    group: true
#    sql-migration-prefix: V
#    sql-migration-separator: __
#    sql-migration-suffixes: .sql
#    schemas: order
#    locations: classpath:db/script